name: Deploy Main to GitHub Pages

on:
  push:
    branches:
      - main
      - feat/snyk

permissions:
  contents: write

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Test vulnerabilities
        working-directory: frontend
        run: snyk test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build CSS bundles
        run: bash ./frontend/build.sh

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true
          clean-exclude: pr-preview
